AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation stack representing core resources of a serverless application.

Parameters:
  AppName:
    Description: "The application name"
    Type: String
    Default: sls-ledger

  EnvCode:
    Description: "The environment code (e.g. dev, uat, prd)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prd

Resources:
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Optionally include the environment name in the table name.
      TableName: !Sub "${AppName}-${EnvCode}-invoices"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  InvoiceLineItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-invoice-line-items"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-payments"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  AttachmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-attachments"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # The bucket name includes the stack name and environment name for uniqueness.
      BucketName: !Sub "${AppName}-${EnvCode}-attachments-bucket"


Outputs:
  InvoicesTableRef:
    Description: "Reference to the Invoices DynamoDB Table (table name)."
    Value: !Ref InvoicesTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-invoices"

  InvoiceLineItemsTableRef:
    Description: "Reference to the Invoice Line Items DynamoDB Table (table name)."
    Value: !Ref InvoiceLineItemsTable
    Export:
      Name: !Sub  "${AppName}-${EnvCode}-invoice-line-items"

  PaymentsTableRef:
    Description: "Reference to the Payments DynamoDB Table (table name)."
    Value: !Ref PaymentsTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-payments"

  AttachmentsTableRef:
    Description: "Reference to the Attachments DynamoDB Table (table name)."
    Value: !Ref AttachmentsTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-attachments"

  AttachmentsBucketName:
    Description: "The name of the Attachments S3 Bucket."
    Value: !Ref AttachmentsBucket
    Export:
      Name: !Sub "${AppName}-${EnvCode}-attachments-bucket"