AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation stack representing core resources of a serverless application.

Parameters:
  AppName:
    Description: "The application name"
    Type: String
    Default: sls-ledger

  EnvCode:
    Description: "The environment code (e.g. dev, uat, prd)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prd

Resources:
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Optionally include the environment name in the table name.
      TableName: !Sub "${AppName}-${EnvCode}-invoices"
      AttributeDefinitions:
        - AttributeName: invoiceID
          AttributeType: S
      KeySchema:
        - AttributeName: invoiceID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  InvoiceLineItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-invoice-line-items"
      AttributeDefinitions:
        - AttributeName: invoiceLineItemID
          AttributeType: S
        - AttributeName: invoiceID
          AttributeType: S
      KeySchema:
        - AttributeName: invoiceLineItemID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InvoiceIndex
          KeySchema:
            - AttributeName: invoiceID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-payments"
      AttributeDefinitions:
        - AttributeName: paymentID
          AttributeType: S
      KeySchema:
        - AttributeName: paymentID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  AttachmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${EnvCode}-attachments"
      AttributeDefinitions:
        - AttributeName: attachmentID
          AttributeType: S
        - AttributeName: invoiceID
          AttributeType: S
      KeySchema:
        - AttributeName: attachmentID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: InvoiceIndex
          KeySchema:
            - AttributeName: invoiceID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref EnvCode

  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # The bucket name includes the stack name and environment name for uniqueness.
      BucketName: !Sub "${AppName}-${EnvCode}-attachments-bucket"

  AppIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${EnvCode}-app-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessAppResourcesPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Permissions for DynamoDB tables
              - Effect: Allow
                Action: 
                  - dynamodb:*
                Resource:
                  - !GetAtt InvoicesTable.Arn
                  - !GetAtt InvoiceLineItemsTable.Arn
                  - !GetAtt PaymentsTable.Arn
                  - !GetAtt AttachmentsTable.Arn
              # Permissions for the S3 bucket and its objects
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${AppName}-${EnvCode}-attachments-bucket"
                  - !Sub "arn:aws:s3:::${AppName}-${EnvCode}-attachments-bucket/*"

Outputs:
  InvoicesTableRef:
    Description: "Reference to the Invoices DynamoDB Table (table name)."
    Value: !Ref InvoicesTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-invoices"

  AppIAMRole:
    Description: "The ARN of the shared IAM role that grants access to all resources."
    Value: !GetAtt AppIAMRole.Arn
    Export:
      Name: !Sub "${AppName}-${EnvCode}-iam-role-arn"

  InvoiceLineItemsTableRef:
    Description: "Reference to the Invoice Line Items DynamoDB Table (table name)."
    Value: !Ref InvoiceLineItemsTable
    Export:
      Name: !Sub  "${AppName}-${EnvCode}-invoice-line-items"

  PaymentsTableRef:
    Description: "Reference to the Payments DynamoDB Table (table name)."
    Value: !Ref PaymentsTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-payments"

  AttachmentsTableRef:
    Description: "Reference to the Attachments DynamoDB Table (table name)."
    Value: !Ref AttachmentsTable
    Export:
      Name: !Sub "${AppName}-${EnvCode}-attachments"

  AttachmentsBucketName:
    Description: "The name of the Attachments S3 Bucket."
    Value: !Ref AttachmentsBucket
    Export:
      Name: !Sub "${AppName}-${EnvCode}-attachments-bucket"